.TH "PEG-E" "6" "February 2014"

.SH "NAME"
peg\-e \- peg elimination solitaire game

.SH "SYNOPSIS"
.PP
.B peg\-e

.SH "DESCRIPTION"
.PP
Peg-E is a peg solitaire game in which you jump over pieces in order to
remove them from the board, ultimately trying to eliminate all but one. The
boards are randomly generated, with 100 levels of difficulty. The game
auto-saves, and has undo-redo capability. Pieces can move horizontally,
vertically, and diagonally.

.SH "COPYRIGHT"
.PP
Copyright \(co 2014 Graeme Gott
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.
.PP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

.SH "AUTHOR"
.PP
Graeme Gott <graeme@gottcode.org>.
